# Data Cleaning

In [1]:
import pandas as pd
import numpy as np

In [2]:
path = "../Resources/Airbnb/listing_clean_col.csv"
hotel_path = "../Resources/Hotel/hotel_data.csv"
listing_df = pd.read_csv(path)
hotel_df = pd.read_csv(hotel_path)
hotel_df.head()

/Applications/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py:3020: DtypeWarning: Columns (7) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)

        City           District    ADR   Month
0  Manhattan  Battery Park City  $100   Jun-18
1  Manhattan            Chelsea  $100   Jun-18
2  Manhattan       East Village  $100   Jun-18
3  Manhattan  Greenwich Village  $100   Jun-18
4  Manhattan     Hell's Kitchen  $100   Jun-18

In [3]:
cols = ["id", "name", "host_since", 
        "neighbourhood_cleansed", "city", "state", "zipcode", 'latitude', 'longitude',
        'property_type', 'room_type', 'accommodates', 'bathrooms', 'bedrooms', "amenities",
        'price', 'cleaning_fee','minimum_nights', 'maximum_nights',
        'number_of_reviews','review_scores_rating',
        'review_scores_accuracy', 'review_scores_cleanliness', 'review_scores_checkin', 'review_scores_communication', 'review_scores_location', 'review_scores_value', 
        'instant_bookable','is_business_travel_ready',
        "host_is_superhost","host_response_time","host_response_rate"]
listing_rdc_df = listing_df[cols]
listing_rdc_df.head()

,id,name,host_since,neighbourhood_cleansed,city,state,zipcode,latitude,longitude,property_type,...,review_scores_cleanliness,review_scores_checkin,review_scores_communication,review_scores_location,review_scores_value,instant_bookable,is_business_travel_ready,host_is_superhost,host_response_time,host_response_rate
0,2539,Clean & quiet apt home by the park,2008-09-07,Kensington,Brooklyn,NY,11218,40.64749,-73.97237,Apartment,...,10.0,10.0,10.0,10.0,10.0,f,f,f,within an hour,100%
1,2595,Skylit Midtown Castle,2008-09-09,Midtown,New York,NY,10018,40.75362,-73.98377,Apartment,...,9.0,10.0,10.0,10.0,9.0,f,f,f,within a few hours,83%
2,3831,Cozy Entire Floor of Brownstone,2008-12-07,Clinton Hill,Brooklyn,NY,11238,40.68514,-73.95976,Guest suite,...,9.0,10.0,10.0,10.0,9.0,f,f,f,within an hour,100%
3,4989,Great 1 bdrm. apartment in the PERFECT location!,2009-01-26,Hell's Kitchen,New York,NY,10036,40.76260,-73.99304,Apartment,...,9.0,10.0,10.0,10.0,9.0,f,f,f,within a day,50%
4,5022,Entire Apt: Spacious Studio/Loft by central park,2009-01-29,East Harlem,New York,NY,10029,40.79851,-73.94399,Apartment,...,9.0,10.0,10.0,9.0,10.0,f,f,f,within an hour,100%

In [4]:
dropna_cols = ["id", "name", "host_since", 
        "neighbourhood_cleansed", "zipcode", 'latitude', 'longitude','amenities',
        'property_type', 'room_type', 'accommodates',
        'price','minimum_nights', 'maximum_nights',
        'number_of_reviews','review_scores_rating',
        'instant_bookable','is_business_travel_ready',
        "host_is_superhost"]
fill_0_cols = ['cleaning_fee']
listing_rdc_dna_df = listing_rdc_df.dropna(subset = dropna_cols)
listing_rdc_dna_df["cleaning_fee"] = listing_rdc_dna_df["cleaning_fee"].fillna(0)

In [5]:
listing_rdc_dna_df.count()

id                             37261
name                           37261
host_since                     37261
neighbourhood_cleansed         37261
city                           37219
state                          37259
zipcode                        37261
latitude                       37261
longitude                      37261
property_type                  37261
room_type                      37261
accommodates                   37261
bathrooms                      37217
bedrooms                       37242
amenities                      37261
price                          37261
cleaning_fee                   37261
minimum_nights                 37261
maximum_nights                 37261
number_of_reviews              37261
review_scores_rating           37261
review_scores_accuracy         37218
review_scores_cleanliness      37235
review_scores_checkin          37199
review_scores_communication    37223
review_scores_location         37196
review_scores_value            37196
instant_bookable               37261
is_business_travel_ready       37261
host_is_superhost              37261
host_response_time             27026
host_response_rate             27026
dtype: int64

# Airbnb Data Cleaning